### ISSUE TITLE
Published jar seems to be empty

### ISSUE THREAD

**Issue by benhutchison** [fmonniot/scala3mock#13]
The jar at https://central.sonatype.com/artifact/eu.monniot/scala3mock-scalatest_3/0.3.1 contains no classfiles. Older versions are the same.

```
$> jar -t -f /Users/ben/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/eu/monniot/scala3mock_3/0.3.1/scala3mock_3-0.3.1.jar
META-INF/MANIFEST.MF
$>
```

**Comment by fmonniot** [comment]
Hi @benhutchison. I see what is going on here. It's a combination of SBT configuration and outdated documentation.

A while back I renamed the core module to `scala3mock-core`, and in the process forgot to not publish the aggregate project. So what's happening is that you are downloading the aggregate project, which indeed does not contain anything. With versions < 0.3.1, you'll have to use `scala3mock_core` instead of `scala3mock`. 

Now, we that being said, I'd rather prefer use the name `scala3mock` instead of `scala3mock-core` for the main dependency. So I'm going to update the repo to use that name instead (and double check the documentation is correct).

**Comment by fmonniot** [comment]
`0.3.2` should have fixed this issue. Thank for trying out this project and reporting bugs!
