### ISSUE TITLE
Mocking trait methods with implicit parameters causing ClassCastException

### ISSUE THREAD

**Issue by voidcontext** [fmonniot/scala3mock#66]
The following code:

```scala

import eu.monniot.scala3mock.macros.{mock, when}
import eu.monniot.scala3mock.ScalaMocks.*


trait Bar[A]

trait Foo:
  def bar[T: Bar](t: T): T

withExpectations() {
  val m: Foo = mock[Foo]

  given Bar[String] = ???

  when[String, String](m.bar).expects(*).returns("mocked result")

  println(m.bar("test"))
}

```

Is causing a runtime(!) exception:

```
java.lang.ClassCastException: class eu.monniot.scala3mock.functions.MockFunction2 cannot be cast to class eu.monniot.scala3mock.functions.MockFunction1 (eu.monniot.scala3mock.functions.MockFunction2 and eu.monniot.scala3mock.functions.MockFunction1 are in unnamed module of loader sbt.internal.ReverseLookupClassLoader @31cc286d)
```

Scastie: https://scastie.scala-lang.org/UFVoHehJTsiSf8xJTbgmTg

**Comment by fmonniot** [comment]
~It's a known issue I think. I haven't looked into the details recently, but when I started working on that project I put that one on the side (see [TestTrait.scala#L29-L33](https://github.com/fmonniot/scala3mock/blob/main/core/src/test/scala/fixtures/TestTrait.scala#L29-L33)) because I didn't knew how to find/declare implicit parameter lists (I still do not mind you).~

edit: nope, I was wrong. See next comment for an accurate answer, sorry for the misdirection. I have also opened https://github.com/fmonniot/scala3mock/pull/67 to add tests for the `using` keyword and the context bound example.

**Comment by fmonniot** [comment]
So I look at this one a bit more and I think the issue comes from the fact that you are forcing the usage of a function with one parameter with `when[String, String]` on a function that has multiple parameters (the implicit being included).

Fundamentally implicit functions are functions with more than one parameter list, and as such if you want to mock then you do have to account for that. Your example work as soon as we change the `when` call to account for the implicit parameter:

```scala
    trait Bar[A]

    trait Foo:
      //def one(a: String): Int
      def bar[T: Bar](t: T): T

    withExpectations() {
      val m: Foo = mockWithDebuggingOutput[Foo]

      given Bar[String] = new Bar[String]{}

      when(m.bar(_: String)(_: Bar[String])).expects(*, *).returns("mocked result")

      println(m.bar("test"))
    }
```

I also realized we have no documentation on how to mock implicit parameters, something we should be improving on for sure.

**Comment by voidcontext** [comment]
@fmonniot Indeed, this works, and I understand now why, thank you for the explanation!
